database:
  url: postgres://root@206.189.54.235:55555/authz?sslmode=disable
migration:
  path: internal/constants/query/schemas
server:
  port: 9000
  timeout: 30s
cors:
  origin:
    - "*"
  allow_credentials: true
  headers:
    - "*"
  methods:
    - GET
    - POST
    - PUT
    - OPTIONS
    - DELETE
    - PATCH
opa:
  path: platform/opa/authz.rego
