database:
  url: postgres://root@localhost:26257/authz?sslmode=disable
  test_url: postgres://root@localhost:26257/defaultdb?sslmode=disable
migration:
  path: internal/constants/query/schemas
server:
  port: 8000
  timeout: 30s
cors:
  origin:
    - "*"
  allow_credentials: true
  headers:
    - "*"
  methods:
    - GET
    - POST
    - PUT
    - OPTIONS
    - DELETE
    - PATCH
opa:
  path: platform/opa/authz.rego