database:
  url: postgres://root@db:26257/defaultdb?sslmode=disable
  idle_conn_timeout: 8m
migration:
  path: internal/constants/query/schemas
  migrate: true
server:
  port: 8000
  timeout: 30s
cors:
  origin:
    - "*"
  allow_credentials: true
  headers:
    - "*"
  methods:
    - GET
    - POST
    - PUT
    - OPTIONS
    - DELETE
    - PATCH
opa:
  path: platform/opa/authz.rego
