// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type Domain struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	ServiceID uuid.UUID    `json:"service_id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type Permission struct {
	ID          uuid.UUID   `json:"id"`
	Status      bool        `json:"status"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Statment    pgtype.JSON `json:"statment"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type PermissionDomain struct {
	ID           uuid.UUID `json:"id"`
	PermissionID uuid.UUID `json:"permission_id"`
	DomainID     uuid.UUID `json:"domain_id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type PermissionsHierarchy struct {
	ID        uuid.UUID `json:"id"`
	Parent    uuid.UUID `json:"parent"`
	Child     uuid.UUID `json:"child"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Role struct {
	ID        uuid.UUID    `json:"id"`
	Status    bool         `json:"status"`
	Name      string       `json:"name"`
	TenantID  string       `json:"tenant_id"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type RolePermission struct {
	ID           uuid.UUID `json:"id"`
	PermissionID uuid.UUID `json:"permission_id"`
	RoleID       uuid.UUID `json:"role_id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Service struct {
	ID        uuid.UUID    `json:"id"`
	Status    bool         `json:"status"`
	Name      string       `json:"name"`
	Password  string       `json:"password"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type Tenant struct {
	ID         uuid.UUID    `json:"id"`
	Status     bool         `json:"status"`
	TenantName string       `json:"tenant_name"`
	ServiceID  uuid.UUID    `json:"service_id"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
}

type TenantUsersRole struct {
	ID        uuid.UUID    `json:"id"`
	TenantID  string       `json:"tenant_id"`
	UserID    uuid.UUID    `json:"user_id"`
	RoleID    uuid.UUID    `json:"role_id"`
	Status    bool         `json:"status"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Status    bool         `json:"status"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}
