// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "2F Capital Support Email",
            "url": "http://www.2fcapital.com",
            "email": "info@1f-capital.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/domains": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "this function create new domain within the service if not exist.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domain"
                ],
                "summary": "create new domain.",
                "parameters": [
                    {
                        "description": "create domain request body",
                        "name": "createdomain",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Domain"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "successfully create new domain",
                        "schema": {
                            "$ref": "#/definitions/dto.Domain"
                        }
                    },
                    "400": {
                        "description": "required field error,bad request error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/permissions": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "this function registers the service if it does already exist.\nif the process finishes with out any error it returns true.\nif the process finishes with any error it returns false.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "permissions"
                ],
                "summary": "register a new permission.",
                "parameters": [
                    {
                        "description": "register permission request body",
                        "name": "creatnewpermission",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePermission"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "successfully register the permission",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "required field error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized service",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "service is not active",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/services": {
            "post": {
                "description": "this function creates new service if it does not already exist.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "create new service.",
                "parameters": [
                    {
                        "description": "create service request body",
                        "name": "createservice",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateService"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "successfully create new service",
                        "schema": {
                            "$ref": "#/definitions/dto.CreateServiceResponse"
                        }
                    },
                    "400": {
                        "description": "required field error,bad request error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "this function deletes the service if it does already exist.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "deletes the service.",
                "parameters": [
                    {
                        "description": "delete service request body",
                        "name": "deleteservice",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successfully deletes the service",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "400": {
                        "description": "required field error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized service",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "service is not active",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "service not found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "invalid input",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreatePermission": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "Action is the urn for the action(method) the user is taking on the resource",
                    "type": "string"
                },
                "description": {
                    "description": "Description is the description of the permission being created",
                    "type": "string"
                },
                "domains": {
                    "description": "Domain is an array that holds the id of the domains the permission is accessible at",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "effect": {
                    "description": "Effect is the effect that's taken on the permission\nIt is either allow or deny",
                    "type": "string"
                },
                "name": {
                    "description": "Name is the name of the permission being created",
                    "type": "string"
                },
                "resource": {
                    "description": "Resource is the urn for the path that is being accessed",
                    "type": "string"
                },
                "service_id": {
                    "description": "ServiceID is the id of the service the permission belongs to",
                    "type": "string"
                }
            }
        },
        "dto.CreateService": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name is the name of the service.",
                    "type": "string"
                },
                "password": {
                    "description": "Password is the secret the service uses to authenticate itself.\nIt is automatically generated when the service is created.",
                    "type": "string"
                },
                "user_id": {
                    "description": "UserId is the id of the user assigned as the super admin for the created service.",
                    "type": "string"
                }
            }
        },
        "dto.CreateServiceResponse": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "Password is the secret the service uses to authenticate itself.\nIt is automatically generated when the service is created.",
                    "type": "string"
                },
                "service": {
                    "description": "Service is the name of the service.",
                    "type": "string"
                },
                "service_id": {
                    "description": "ServiceID is the unique identifier for the created service.",
                    "type": "string"
                },
                "service_status": {
                    "description": "ServiceStatus is the status of the service.\nIt is set to false when the service is created.",
                    "type": "boolean"
                },
                "tenant": {
                    "description": "Tenant is the domain the super admin is in.\nIt is automatically created upon the creation of the service.",
                    "type": "string"
                }
            }
        },
        "dto.Domain": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "CreatedAt is the  time this domain created at.",
                    "type": "string"
                },
                "deleted_at": {
                    "description": "DeletedAt is the time this domain was deleted.",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier for the domain\nIt is automatically generated when the domain is created.",
                    "type": "string"
                },
                "name": {
                    "description": "Name is the name of the domain",
                    "type": "string"
                },
                "service_id": {
                    "description": "ServiceID is the id of the service which own the domain.",
                    "type": "string"
                },
                "updated_at": {
                    "description": "CreatedAt is the  time this domain updated at.",
                    "type": "string"
                }
            }
        },
        "model.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code is the error code. It is not status code",
                    "type": "integer"
                },
                "description": {
                    "description": "Description is the error description.",
                    "type": "string"
                },
                "field_error": {
                    "description": "FieldError is the error detail for each field, if available that is.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.FieldError"
                    }
                },
                "message": {
                    "description": "Message is the error message.",
                    "type": "string"
                },
                "stack_trace": {
                    "description": "StackTrace is the stack trace of the error.\nIt is only returned for debugging",
                    "type": "string"
                }
            }
        },
        "model.FieldError": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "Description is the error description for this field.",
                    "type": "string"
                },
                "name": {
                    "description": "Name is the name of the field that caused the error.",
                    "type": "string"
                }
            }
        },
        "model.Request": {
            "type": "object",
            "properties": {
                "action": {
                    "description": "Action  is the urn of the action the user is taking on the resource.",
                    "type": "string"
                },
                "resource": {
                    "description": "Resource is the urn for the resource the user is trying to take action on.",
                    "type": "string"
                },
                "service": {
                    "description": "Service is the id of the service.\nIt is set by the server after authenticating the service.",
                    "type": "string"
                },
                "subject": {
                    "description": "Subject is the user id who is trying to take action on the resource.",
                    "type": "string"
                },
                "tenant": {
                    "description": "Tenant is the scope the user is operating.\nIt is set to \"administrator\" if it is not provided.",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8000",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Authorization API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
